// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jegoftddzcbtqaqehwdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ29mdGRkemNidHFhcWVod2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzUxOTEsImV4cCI6MjA1OTg1MTE5MX0.N6qvOdFt7JtleWdQ5MCNwsPDOFh7HwHpKSUADJjFMP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);